#!/usr/bin/env python3
"""
End-to-end example of using the Jira integration.

This script demonstrates how to:
1. Create mock use cases
2. Configure the Jira exporter
3. Export use cases to Jira

Note: This is a demonstration script. In real usage, use cases would be
generated by RE-cue's analyzer from actual source code.
"""

import os
import sys
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from reverse_engineer.domain import UseCase
from reverse_engineer.exporters import JiraConfig, JiraExporter


def create_example_use_cases():
    """Create example use cases for demonstration."""
    return [
        UseCase(
            id="UC01",
            name="Create User Account",
            primary_actor="User",
            secondary_actors=["Email Service", "Payment Gateway"],
            preconditions=[
                "User is not logged in",
                "Registration is enabled",
                "Email is unique in the system",
            ],
            postconditions=[
                "User account is created in the database",
                "Welcome email is sent to user",
                "User is redirected to login page",
            ],
            main_scenario=[
                "User navigates to registration page",
                "User enters email, password, and profile information",
                "System validates input format",
                "System checks email uniqueness",
                "System creates user account",
                "System sends welcome email",
                "System displays success message",
            ],
            extensions=[
                "3a. Invalid email format - Display error message and remain on page",
                "4a. Email already exists - Display error and suggest login",
                "6a. Email service unavailable - Create account but log error for retry",
            ],
            identified_from=[
                "UserController.register()",
                "RegistrationService.createAccount()",
                "@PostMapping('/api/users/register')",
            ],
        ),
        UseCase(
            id="UC02",
            name="Process Payment",
            primary_actor="Customer",
            secondary_actors=["Payment Gateway", "Order Service"],
            preconditions=[
                "Customer is logged in",
                "Shopping cart contains items",
                "Payment information is valid",
            ],
            postconditions=[
                "Payment is processed successfully",
                "Order is created in the system",
                "Confirmation email is sent",
            ],
            main_scenario=[
                "Customer proceeds to checkout",
                "System displays order summary",
                "Customer enters payment information",
                "System validates payment details",
                "System processes payment via gateway",
                "System creates order record",
                "System sends confirmation email",
            ],
            extensions=[
                "4a. Invalid card details - Display error and allow retry",
                "5a. Payment declined - Display error and suggest alternative payment",
                "5b. Payment gateway timeout - Display error and retry automatically",
            ],
            identified_from=[
                "PaymentController.processPayment()",
                "PaymentService.authorizePayment()",
                "@Transactional(propagation=REQUIRED, isolation=READ_COMMITTED)",
            ],
        ),
    ]


def main():
    """Main function demonstrating Jira integration."""
    print("=" * 70)
    print("RE-cue Jira Integration - Example Demonstration")
    print("=" * 70)
    print()

    # Check for required environment variables
    jira_url = os.getenv("JIRA_URL")
    jira_user = os.getenv("JIRA_USER")
    jira_token = os.getenv("JIRA_API_TOKEN")
    jira_project = os.getenv("JIRA_PROJECT_KEY")

    if not all([jira_url, jira_user, jira_token, jira_project]):
        print("⚠️  This is a demonstration script showing how to use Jira integration.")
        print()
        print("To actually export to Jira, set these environment variables:")
        print("  - JIRA_URL")
        print("  - JIRA_USER")
        print("  - JIRA_API_TOKEN")
        print("  - JIRA_PROJECT_KEY")
        print()
        print("Example:")
        print('  export JIRA_URL="https://example.atlassian.net"')
        print('  export JIRA_USER="user@example.com"')
        print('  export JIRA_API_TOKEN="your-token"')
        print('  export JIRA_PROJECT_KEY="PROJ"')
        print()
        print("=" * 70)
        print("Example Use Cases (would be exported to Jira):")
        print("=" * 70)
        print()

        # Show what would be exported
        use_cases = create_example_use_cases()
        for uc in use_cases:
            print(f"📋 {uc.id}: {uc.name}")
            print(f"   Primary Actor: {uc.primary_actor}")
            print(f"   Preconditions: {len(uc.preconditions)}")
            print(f"   Main Scenario: {len(uc.main_scenario)} steps")
            print(f"   Extensions: {len(uc.extensions)}")
            print()

        return

    # Create configuration
    print("📝 Creating Jira configuration...")
    config = JiraConfig(
        server=jira_url,
        username=jira_user,
        api_token=jira_token,
        project_key=jira_project,
        issue_type="Story",
    )
    print(f"   Server: {config.server}")
    print(f"   Project: {config.project_key}")
    print(f"   Issue Type: {config.issue_type}")
    print()

    # Create exporter
    print("🔧 Initializing Jira exporter...")
    try:
        exporter = JiraExporter(config)
    except ImportError as e:
        print(f"❌ Error: {e}")
        print()
        print("Install the jira library with:")
        print("  pip install jira>=3.0.0")
        return
    print("   ✓ Exporter initialized")
    print()

    # Test connection
    print("🔗 Testing connection to Jira...")
    if not exporter.test_connection():
        print("❌ Connection failed. Please check your credentials and URL.")
        return
    print("   ✓ Connection successful")
    print()

    # Create example use cases
    print("📋 Creating example use cases...")
    use_cases = create_example_use_cases()
    print(f"   Created {len(use_cases)} use cases")
    print()

    # Export to Jira
    print("🚀 Exporting use cases to Jira...")
    results = exporter.export_use_cases(use_cases)
    print()

    # Report results
    print("=" * 70)
    print("Export Results")
    print("=" * 70)
    print()

    success_count = sum(1 for r in results if r.success)
    fail_count = len(results) - success_count

    for result in results:
        if result.success:
            print(f"✅ {result.use_case_name}")
            print(f"   Issue Key: {result.issue_key}")
            print(f"   URL: {result.issue_url}")
        else:
            print(f"❌ {result.use_case_name}")
            print(f"   Error: {result.error_message}")
        print()

    print("=" * 70)
    print(f"Summary: {success_count} succeeded, {fail_count} failed")
    print("=" * 70)


if __name__ == "__main__":
    main()
