name: 'RE-cue Code Analysis'
description: 'Analyze your codebase and generate comprehensive documentation with RE-cue'
author: 'cue-3'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  project-path:
    description: 'Path to the project to analyze (default: current directory)'
    required: false
    default: '.'
  
  description:
    description: 'Project description for specification generation'
    required: false
    default: 'Automated code analysis'
  
  generate-spec:
    description: 'Generate specification document (spec.md)'
    required: false
    default: 'true'
  
  generate-plan:
    description: 'Generate implementation plan (plan.md)'
    required: false
    default: 'true'
  
  generate-data-model:
    description: 'Generate data model documentation (data-model.md)'
    required: false
    default: 'true'
  
  generate-api-contract:
    description: 'Generate OpenAPI contract (api-spec.json)'
    required: false
    default: 'true'
  
  generate-use-cases:
    description: 'Generate phased analysis documents (phase1-structure.md through phase4-use-cases.md)'
    required: false
    default: 'true'
  
  generate-fourplusone:
    description: 'Generate 4+1 Architecture View document (fourplusone-architecture.md)'
    required: false
    default: 'true'
  
  generate-all:
    description: 'Generate all documentation types (overrides individual flags)'
    required: false
    default: 'false'
  
  output-dir:
    description: 'Output directory for generated documentation'
    required: false
    default: 'docs/generated'
  
  commit-changes:
    description: 'Automatically commit generated documentation'
    required: false
    default: 'false'
  
  commit-message:
    description: 'Commit message for generated documentation'
    required: false
    default: 'docs: Update generated documentation [skip ci]'

outputs:
  endpoints-found:
    description: 'Number of API endpoints discovered'
    value: ${{ steps.analyze.outputs.endpoints }}
  
  models-found:
    description: 'Number of data models discovered'
    value: ${{ steps.analyze.outputs.models }}
  
  services-found:
    description: 'Number of services discovered'
    value: ${{ steps.analyze.outputs.services }}
  
  documentation-path:
    description: 'Path to generated documentation'
    value: ${{ steps.analyze.outputs.doc_path }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install RE-cue dependencies
      shell: bash
      run: |
        pip install jinja2 pyyaml
    
    - name: Install RE-cue
      shell: bash
      run: |
        cd ${{ github.action_path }}/../../../reverse-engineer-python
        pip install -e .
    
    - name: Create output directory
      shell: bash
      run: |
        mkdir -p ${{ inputs.output-dir }}
    
    - name: Run RE-cue Analysis
      id: analyze
      shell: bash
      run: |
        # Build command arguments
        ARGS=""
        
        # Check for generate-all flag first
        if [ "${{ inputs.generate-all }}" = "true" ]; then
          ARGS="--spec --plan --data-model --api-contract --use-cases --fourplusone"
        else
          # Individual flags
          if [ "${{ inputs.generate-spec }}" = "true" ]; then
            ARGS="$ARGS --spec"
          fi
          
          if [ "${{ inputs.generate-plan }}" = "true" ]; then
            ARGS="$ARGS --plan"
          fi
          
          if [ "${{ inputs.generate-data-model }}" = "true" ]; then
            ARGS="$ARGS --data-model"
          fi
          
          if [ "${{ inputs.generate-api-contract }}" = "true" ]; then
            ARGS="$ARGS --api-contract"
          fi
          
          if [ "${{ inputs.generate-use-cases }}" = "true" ]; then
            ARGS="$ARGS --use-cases"
          fi
          
          if [ "${{ inputs.generate-fourplusone }}" = "true" ]; then
            ARGS="$ARGS --fourplusone"
          fi
        fi
        
        # Run analysis
        cd ${{ inputs.project-path }}
        python -m reverse_engineer \
          $ARGS \
          --description "${{ inputs.description }}" \
          --output ${{ inputs.output-dir }} \
          --verbose 2>&1 | tee analysis.log
        
        # Extract metrics from log
        ENDPOINTS=$(grep -oP 'Found \K\d+(?= endpoints)' analysis.log | tail -1 || echo "0")
        MODELS=$(grep -oP 'Found \K\d+(?= models)' analysis.log | tail -1 || echo "0")
        SERVICES=$(grep -oP 'Found \K\d+(?= services)' analysis.log | tail -1 || echo "0")
        
        echo "endpoints=$ENDPOINTS" >> $GITHUB_OUTPUT
        echo "models=$MODELS" >> $GITHUB_OUTPUT
        echo "services=$SERVICES" >> $GITHUB_OUTPUT
        echo "doc_path=${{ inputs.output-dir }}" >> $GITHUB_OUTPUT
        
        rm -f analysis.log
    
    - name: Commit generated documentation
      if: inputs.commit-changes == 'true'
      shell: bash
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        git add ${{ inputs.output-dir }}
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "${{ inputs.commit-message }}"
          git push
        fi
